/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    war
}

dependencies {
    api(libs.com.sun.jersey.jersey.server)
    api(libs.log4j.log4j)
    api(libs.org.quartz.scheduler.quartz)
    api(project(":ikey-plus-api"))
    providedCompile(libs.javax.servlet.servlet.api)
}

description = "ikey-plus-rest"
